# Generated by Django 4.2.30 on 2026-04-18 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('stage', models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], default='PLANTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_updates', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='fields.field')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
